/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it.cnr.ilc.lexo.sparql;

/**
 *
 * @author andreabellandi
 */
public class SparqlIndex {

    public static final String LEXICAL_ENTRY_INDEX
            = SparqlPrefix.INST.getSparqlPrefix() + "\n"
            + SparqlPrefix.LUC.getSparqlPrefix() + "\n"
            + "INSERT DATA {\n"
            + "     inst:" + SparqlVariable.LEXICAL_ENTRY_INDEX + " :createConnector '''\n"
            + "{\n"
            + "   \"types\": [\n"
            + "     \"http://www.w3.org/ns/lemon/ontolex#LexicalEntry\"\n"
            + "   ],\n"
            + "   \"fields\": [\n"
            + "     {\n"
            + "       \"fieldName\": \"lexicalEntryLabel\",\n"
            + "       \"propertyChain\": [\n"
            + "        \"http://www.w3.org/2000/01/rdf-schema#label\"\n"
            + "       ],\n"
            + "      \"multivalued\": false,\n"
            + "      \"analyzed\": false\n"
            + "     },\n"
            + "     {   \n"
            + "      \"fieldName\": \"writtenOtherForm\",\n"
            + "      \"propertyChain\": [\n"
            + "        \"http://www.w3.org/ns/lemon/ontolex#otherForm\",\n"
            + "        \"http://www.w3.org/ns/lemon/ontolex#writtenRep\"\n"
            + "      ],\n"
            + "      \"analyzed\": false\n"
            + "     },\n"
            + "     {\n"
            + "      \"fieldName\": \"writtenCanonicalForm\",\n"
            + "      \"propertyChain\": [\n"
            + "        \"http://www.w3.org/ns/lemon/ontolex#canonicalForm\",\n"
            + "        \"http://www.w3.org/ns/lemon/ontolex#writtenRep\"\n"
            + "      ],\n"
            + "      \"analyzed\": false\n"
            + "     },\n"
            + "    {\n"
            + "       \"fieldName\": \"lexicalEntryIRI\",\n"
            + "       \"propertyChain\": [\n"
            + "         \"$self\"\n"
            + "       ],\n"
            + "	\"multivalued\": false,\n"
            + "    \"analyzed\": false\n"
            + "    },\n"
            + "    {\n"
            + "         \"fieldName\": \"writtenFormLanguage\",\n"
            + "         \"propertyChain\": [\n"
            + "           \"http://www.w3.org/2000/01/rdf-schema#label\",\n"
            + "           \"lang()\"\n"
            + "         ],\n"
            + "         \"analyzed\": false\n"
            + "     },\n"
            + "     {\n"
            + "         \"fieldName\": \"type\",\n"
            + "         \"propertyChain\": [\n"
            + "           \"http://www.w3.org/1999/02/22-rdf-syntax-ns#type\",\n"
            + "           \"http://www.w3.org/2000/01/rdf-schema#label\"\n"
            + "         ],\n"
            + "         \"analyzed\": false,\n"
            + "         \"languages\": [\n"
            + "			\"en\"\n"
            + "         ]\n"
            + "     },\n"
            + "     {\n"
            + "         \"fieldName\": \"pos\",\n"
            + "         \"propertyChain\": [\n"
            + "           \"http://www.lexinfo.net/ontology/3.0/lexinfo#partOfSpeech\",\n"
            + "           \"http://www.w3.org/2000/01/rdf-schema#label\"\n"
            + "         ],\n"
            + "         \"analyzed\": false,\n"
            + "         \"languages\": [\n"
            + "			\"en\"\n"
            + "         ]\n"
            + "     },\n"
            + "     {\n"
            + "          \"fieldName\": \"status\",\n"
            + "          \"propertyChain\": [\n"
            + "                \"http://www.w3.org/2003/06/sw-vocab-status/ns#term_status\"\n"
            + "          ]\n"
            + "     },\n"
            + "    {\n"
            + "          \"fieldName\": \"author\",\n"
            + "          \"propertyChain\": [\n"
            + "                \"http://purl.org/dc/terms/creator\"\n"
            + "          ]\n"
            + "     }\n"
            + "   ]\n"
            + " }\n"
            + " ''' .\n"
            + " }";

    public static final String FORM_INDEX
            = "PREFIX inst: <http://www.ontotext.com/connectors/lucene/instance#>\n"
            + "PREFIX : <http://www.ontotext.com/connectors/lucene#>\n"
            + "INSERT DATA {\n"
            + "     inst:formIndex :createConnector '''\n"
            + " {\n"
            + "   \"types\": [\n"
            + "     \"http://www.w3.org/ns/lemon/ontolex#Form\"\n"
            + "   ],\n"
            + "   \"fields\": [\n"
            + "     {   \n"
            + "      \"fieldName\": \"writtenRep\",\n"
            + "      \"propertyChain\": [\n"
            + "        \"http://www.w3.org/ns/lemon/ontolex#writtenRep\"\n"
            + "      ],\n"
            + "      \"multivalued\": false,\n"
            + "      \"analyzed\": false\n"
            + "     },\n"
            + "     {\n"
            + "      \"fieldName\": \"phoneticRep\",\n"
            + "      \"propertyChain\": [\n"
            + "        \"http://www.w3.org/ns/lemon/ontolex#phoneticRep\"\n"
            + "      ],\n"
            + "      \"multivalued\": false,\n"
            + "      \"analyzed\": false\n"
            + "     },\n"
            + "     {\n"
            + "      \"fieldName\": \"pronunciation\",\n"
            + "      \"propertyChain\": [\n"
            + "        \"http://www.lexinfo.net/ontology/3.0/lexinfo#pronunciation\"\n"
            + "      ],\n"
            + "      \"multivalued\": false,\n"
            + "      \"analyzed\": false\n"
            + "     },\n"
            + "     {\n"
            + "      \"fieldName\": \"romanization\",\n"
            + "      \"propertyChain\": [\n"
            + "        \"http://www.lexinfo.net/ontology/3.0/lexinfo#romanization\"\n"
            + "      ],\n"
            + "      \"multivalued\": false,\n"
            + "      \"analyzed\": false\n"
            + "     },\n"
            + "     {\n"
            + "      \"fieldName\": \"segmentation\",\n"
            + "      \"propertyChain\": [\n"
            + "        \"http://www.lexinfo.net/ontology/3.0/lexinfo#segmentation\"\n"
            + "      ],\n"
            + "      \"multivalued\": false,\n"
            + "      \"analyzed\": false\n"
            + "     },\n"
            + "     {\n"
            + "      \"fieldName\": \"transliteration\",\n"
            + "      \"propertyChain\": [\n"
            + "        \"http://www.lexinfo.net/ontology/3.0/lexinfo#transliteration\"\n"
            + "      ],\n"
            + "      \"multivalued\": false,\n"
            + "      \"analyzed\": false\n"
            + "     },\n"
            + "    {\n"
            + "       \"fieldName\": \"formIRI\",\n"
            + "       \"propertyChain\": [\n"
            + "         \"$self\"\n"
            + "       ],\n"
            + "	\"multivalued\": false,\n"
            + "    \"analyzed\": false\n"
            + "    },\n"
            + "    {\n"
            + "    \"fieldName\": \"writtenFormLanguage\",\n"
            + "    \"propertyChain\": [\n"
            + "       \"http://www.w3.org/2000/01/rdf-schema#label\",\n"
            + "       \"lang()\"\n"
            + "     ],\n"
            + "     \"analyzed\": false\n"
            + "     }\n"
            + "   ]\n"
            + " }\n"
            + " ''' .\n"
            + " }";

    public static final String LEXICAL_SENSE_INDEX = ""
            + "PREFIX inst: <http://www.ontotext.com/connectors/lucene/instance#>\n"
            + "PREFIX : <http://www.ontotext.com/connectors/lucene#>\n"
            + "INSERT DATA {\n"
            + "     inst:lexicalSenseIndex :createConnector '''\n"
            + " {\n"
            + "   \"types\": [\n"
            + "     \"http://www.w3.org/ns/lemon/ontolex#LexicalSense\"\n"
            + "   ],\n"
            + "   \"fields\": [\n"
            + "     {   \n"
            + "      \"fieldName\": \"definition\",\n"
            + "      \"propertyChain\": [\n"
            + "        \"http://www.w3.org/2004/02/skos/core#definition\"\n"
            + "      ],\n"
            + "      \"multivalued\": false,\n"
            + "      \"analyzed\": false\n"
            + "     },\n"
            + "{   \n"
            + "      \"fieldName\": \"description\",\n"
            + "      \"propertyChain\": [\n"
            + "        \"http://www.lexinfo.net/ontology/3.0/lexinfo#description\"\n"
            + "      ],\n"
            + "      \"multivalued\": false,\n"
            + "      \"analyzed\": false\n"
            + "     },\n"
            + "{   \n"
            + "      \"fieldName\": \"etymology\",\n"
            + "      \"propertyChain\": [\n"
            + "        \"http://www.lexinfo.net/ontology/3.0/lexinfo#etymology\"\n"
            + "      ],\n"
            + "      \"multivalued\": false,\n"
            + "      \"analyzed\": false\n"
            + "     },\n"
            + "{   \n"
            + "      \"fieldName\": \"explanation\",\n"
            + "      \"propertyChain\": [\n"
            + "        \"http://www.lexinfo.net/ontology/3.0/lexinfo#explanation\"\n"
            + "      ],\n"
            + "      \"multivalued\": false,\n"
            + "      \"analyzed\": false\n"
            + "     },\n"
            + "{   \n"
            + "      \"fieldName\": \"gloss\",\n"
            + "      \"propertyChain\": [\n"
            + "        \"http://www.lexinfo.net/ontology/3.0/lexinfo#gloss\"\n"
            + "      ],\n"
            + "      \"multivalued\": false,\n"
            + "      \"analyzed\": false\n"
            + "     },\n"
            + "{   \n"
            + "      \"fieldName\": \"senseExample\",\n"
            + "      \"propertyChain\": [\n"
            + "        \"http://www.lexinfo.net/ontology/3.0/lexinfo#senseExample\"\n"
            + "      ],\n"
            + "      \"multivalued\": false,\n"
            + "      \"analyzed\": false\n"
            + "     },\n"
            + "    {   \n"
            + "      \"fieldName\": \"senseTranslation\",\n"
            + "      \"propertyChain\": [\n"
            + "        \"http://www.lexinfo.net/ontology/3.0/lexinfo#senseTranslation\"\n"
            + "      ],\n"
            + "      \"multivalued\": false,\n"
            + "      \"analyzed\": false\n"
            + "     },\n"
            + "    {\n"
            + "       \"fieldName\": \"lexicalSenseIRI\",\n"
            + "       \"propertyChain\": [\n"
            + "         \"$self\"\n"
            + "       ],\n"
            + "	\"multivalued\": false,\n"
            + "    \"analyzed\": false\n"
            + "    }\n"
            + "   ]\n"
            + " }\n"
            + " ''' .\n"
            + " }";

    public static final String DELETE_INDEX
            = SparqlPrefix.INST.getSparqlPrefix() + "\n"
            + "INSERT DATA {\n"
            + "  inst:[INDEX_NAME] :dropConnector \"\" .\n"
            + "}";

    public static String CONCEPT_REFERENCE_INDEX = "PREFIX inst: <http://www.ontotext.com/connectors/lucene/instance#>\n"
            + "PREFIX : <http://www.ontotext.com/connectors/lucene#>\n"
            + "INSERT DATA {\n"
            + "     inst:conceptReferenceIndex :createConnector '''\n"
            + " {\n"
            + "   \"types\": [\n"
            + "     \"http://www.w3.org/ns/lemon/ontolex#LexicalSense\"\n"
            + "   ],\n"
            + "   \"fields\": [\n"
            + "    {\n"
            + "       \"fieldName\": \"referencedBy\",\n"
            + "       \"propertyChain\": [\n"
            + "        \"http://www.w3.org/ns/lemon/ontolex#reference\"\n"
            + "       ],\n"
            + "    \"analyzed\": false\n"
            + "    },\n"
            + "{\n"
            + "       \"fieldName\": \"lemma\",\n"
            + "       \"propertyChain\": [\n"
            + "        \"http://www.w3.org/ns/lemon/ontolex#isSenseOf\",\n"
            + "        \"http://www.w3.org/ns/lemon/ontolex#canonicalForm\",\n"
            + "        \"http://www.w3.org/ns/lemon/ontolex#writtenRep\",\n"
            + "       ],\n"
            + "\"multivalued\": false,\n"
            + "    \"analyzed\": false\n"
            + "    }\n"
            + "   ]\n"
            + " }\n"
            + " ''' .\n"
            + " }";

    public static String ETYMOLOGY_INDEX = "PREFIX inst: <http://www.ontotext.com/connectors/lucene/instance#>\n"
            + "PREFIX : <http://www.ontotext.com/connectors/lucene#>\n"
            + "INSERT DATA {\n"
            + "     inst:etymologyIndex :createConnector '''\n"
            + " {\n"
            + "   \"types\": [\n"
            + "     \"http://lari-datasets.ilc.cnr.it/lemonEty#Etymology\"\n"
            + "   ],\n"
            + "   \"fields\": [\n"
            + "     {   \n"
            + "      \"fieldName\": \"label\",\n"
            + "      \"propertyChain\": [\n"
            + "        \"http://www.w3.org/2000/01/rdf-schema#label\"\n"
            + "      ],\n"
            + "      \"multivalued\": false,\n"
            + "      \"analyzed\": false\n"
            + "     },\n"
            + "    {\n"
            + "       \"fieldName\": \"etymologyIRI\",\n"
            + "       \"propertyChain\": [\n"
            + "         \"$self\"\n"
            + "       ],\n"
            + "	\"multivalued\": false,\n"
            + "    \"analyzed\": false\n"
            + "    },\n"
            + "     {   \n"
            + "      \"fieldName\": \"author\",\n"
            + "      \"propertyChain\": [\n"
            + "        \"http://purl.org/dc/terms/creator\"\n"
            + "      ],\n"
            + "      \"multivalued\": false,\n"
            + "      \"analyzed\": false\n"
            + "     }\n"
            + "   ]\n"
            + " }\n"
            + " ''' .\n"
            + " }";

    public static String COMPONENT_INDEX = "PREFIX inst: <http://www.ontotext.com/connectors/lucene/instance#>\n"
            + "PREFIX : <http://www.ontotext.com/connectors/lucene#>\n"
            + "INSERT DATA {\n"
            + "     inst:componentIndex :createConnector '''\n"
            + " {\n"
            + "   \"types\": [\n"
            + "     \"http://www.w3.org/ns/lemon/decomp#Component\"\n"
            + "   ],\n"
            + "   \"fields\": [\n"
            + "     {\n"
            + "       \"fieldName\": \"componentLabel\",\n"
            + "       \"propertyChain\": [\n"
            + "        \"http://www.w3.org/2000/01/rdf-schema#label\"\n"
            + "       ],\n"
            + "      \"multivalued\": false,\n"
            + "      \"analyzed\": false\n"
            + "     },\n"
            + "     {\n"
            + "       \"fieldName\": \"ComponentIRI\",\n"
            + "       \"propertyChain\": [\n"
            + "         \"$self\"\n"
            + "       ],\n"
            + "	\"multivalued\": false,\n"
            + "    \"analyzed\": false\n"
            + "    },\n"
            + "     {\n"
            + "         \"fieldName\": \"morpho\",\n"
            + "         \"propertyChain\": [\n"
            + "           \"http://www.lexinfo.net/ontology/3.0/lexinfo#morphosyntacticProperty\",\n"
            + "           \"http://www.w3.org/2000/01/rdf-schema#label\"\n"
            + "         ],\n"
            + "         \"analyzed\": false,\n"
            + "         \"languages\": [\n"
            + "			\"en\"\n"
            + "         ]\n"
            + "     },\n"
            + "    {\n"
            + "          \"fieldName\": \"author\",\n"
            + "          \"propertyChain\": [\n"
            + "                \"http://purl.org/dc/terms/creator\"\n"
            + "          ]\n"
            + "     }\n"
            + "   ]\n"
            + " }\n"
            + " ''' .\n"
            + " }";

    public static String LEXICAL_CONCEPT_INDEX = "PREFIX inst: <http://www.ontotext.com/connectors/lucene/instance#>\n"
            + "PREFIX : <http://www.ontotext.com/connectors/lucene#>\n"
            + "INSERT DATA {\n"
            + "     inst:lexicalConceptIndex :createConnector '''\n"
            + " {\n"
            + "   \"types\": [\n"
            + "     \"http://www.w3.org/ns/lemon/ontolex#LexicalConcept\"\n"
            + "   ],\n"
            + "   \"fields\": [\n"
            + "     {\n"
            + "       \"fieldName\": \"lexicalConceptLabel\",\n"
            + "       \"propertyChain\": [\n"
            + "        \"http://www.w3.org/2000/01/rdf-schema#label\"\n"
            + "       ],\n"
            + "     \"multivalued\": false\n"
            + "     },\n"
            + "     {   \n"
            + "      \"fieldName\": \"lexicalEntry\",\n"
            + "      \"propertyChain\": [\n"
            + "        \"http://www.w3.org/ns/lemon/ontolex#isEvokedBy\"\n"
            + "      ],\n"
            + "      \"multivalued\": false,\n"
            + "      \"analyzed\": false\n"
            + "     },\n"
            + "     {\n"
            + "      \"fieldName\": \"lexicalSense\",\n"
            + "      \"propertyChain\": [\n"
            + "        \"http://www.w3.org/ns/lemon/ontolex#lexicalizedSense\"\n"
            + "      ],\n"
            + "      \"multivalued\": false,\n"
            + "      \"analyzed\": false\n"
            + "     },\n"
            + "    {\n"
            + "       \"fieldName\": \"lexicalConceptIRI\",\n"
            + "       \"propertyChain\": [\n"
            + "         \"$self\"\n"
            + "       ],\n"
            + "	\"multivalued\": false,\n"
            + "    \"analyzed\": false\n"
            + "    },\n"
            + "     {\n"
            + "         \"fieldName\": \"definition\",\n"
            + "         \"propertyChain\": [\n"
            + "           \"http://www.w3.org/2004/02/skos/core#definition\"\n"
            + "         ]\n"
            + "     },\n"
            + "    {\n"
            + "          \"fieldName\": \"author\",\n"
            + "          \"propertyChain\": [\n"
            + "                \"http://purl.org/dc/terms/creator\"\n"
            + "          ]\n"
            + "     }\n"
            + "   ]\n"
            + " }\n"
            + " ''' .\n"
            + " }";
}
